### ISSUE TITLE
This is stolen library!

### ISSUE THREAD

**Issue by iammert** [amineghabi/ProgressLayout#1]
This is a stolen library which is written by me. I dont understand why people do that. Please dont star this repo and make the real one up. 
Here is the original. https://github.com/iammert/ProgressLayout
You can check other libraries of this person. They are also written by me. you can find them on my github page.

**Comment by ppamorim** [comment]
That is a sad day :(

**Comment by kozaxinan** [comment]
This is kind of steal. You should be banned.
